# Generated by Django 3.1.8 on 2023-04-12 02:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0002_auto_20230119_0810'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='Rating',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='review',
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('movie', 'reviewer')},
        ),
    ]
