# Generated by Django 3.1.8 on 2023-02-16 15:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0002_auto_20230119_0810'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='Rating',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='review',
        ),
        migrations.AddField(
            model_name='movie',
            name='avg_rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
