# Generated by Django 3.1.8 on 2023-04-28 08:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0003_auto_20230428_1328'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('movie', 'reviewer')},
        ),
    ]
