# Generated by Django 3.1.8 on 2023-04-29 18:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0003_auto_20230429_1310"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rating",
            old_name="reviewer",
            new_name="creator",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="avg_rating",
        ),
        migrations.AlterField(
            model_name="rating",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
