# Generated by Django 3.1.8 on 2023-04-15 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20230415_0550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='reviewer',
            new_name='creator',
        ),
        migrations.AlterField(
            model_name='rating',
            name='score',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
    ]
