# Generated by Django 3.1.8 on 2023-02-17 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0004_movie_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='score',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='movie',
            name='inappropriate_status',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('unresolved', 'Unresolved'), ('inappropriate', 'Inappropriate'), ('Reject', 'Reject')], default='unresolved', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_movie', to='movies.movie')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_reviewer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
