# Generated by Django 3.1.8 on 2023-04-12 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20230412_0916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='reviewer',
            new_name='creator',
        ),
    ]
