# Generated by Django 3.1.8 on 2023-04-15 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0004_auto_20230415_0711'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_inappropriate',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='MovieReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('unresolved', 'Unresolved'), ('marked_inappropriate', 'Marked as Inappropriate'), ('rejected', 'Rejected')], default='unresolved', max_length=20)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_created', to=settings.AUTH_USER_MODEL)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='movies.movie')),
            ],
        ),
    ]
