# Generated by Django 3.1.8 on 2023-02-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20230217_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='deleted',
            field=models.BooleanField(default=True),
        ),
    ]
