# Generated by Django 3.1.8 on 2023-04-28 12:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0006_report'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('movie', 'reviewer')},
        ),
    ]
