# Generated by Django 3.1.8 on 2023-02-16 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20230216_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='state',
            field=models.CharField(blank=True, choices=[('Mark movie as inappropriate', 'Mark movie as inappropriate'), ('Reject report', 'Reject report')], default='unresolved', max_length=255, null=True),
        ),
    ]
