# Generated by Django 3.1.8 on 2023-04-12 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20230411_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_hidden',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
