# Generated by Django 3.1.8 on 2023-02-16 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_report_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='visibility',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='state',
            field=models.CharField(blank=True, choices=[('unresolved', 'unresolved'), ('Mark movie as inappropriate', 'Mark movie as inappropriate'), ('Reject report', 'Reject report')], default='unresolved', max_length=255, null=True),
        ),
    ]
