# Generated by Django 3.1.8 on 2023-04-12 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_movie_is_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_report_closed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
